---
- name: Установка ClickHouse (dry-run)
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - clickhouse
  vars:
    clickhouse_version: "22.3.3.44"

- name: Установка Vector (dry-run)
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - vector_role
  vars:
    clickhouse_host: "localhost"
    # Упрощенная конфигурация для теста
    vector_sinks:
      test_clickhouse:
        type: clickhouse
        inputs: ["demo_logs"]
        host: "localhost"
        port: 8123
        database: "test"
        table: "logs"

- name: Установка Lighthouse (dry-run)
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - lighthouse_role
