---
- src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
  scm: git
  version: "1.13"
  name: clickhouse

- src: https://github.com/dreadnone/vector-role.git
  scm: git
  version: "v1.0.0"
  name: vector_role

- src: https://github.com/dreadnone/lighthouse-role.git
  scm: git
  version: "v1.0.0"
  name: lighthouse_role
