---
- name: Установка ClickHouse
  hosts: clickhouse
  gather_facts: yes  # ДОБАВИЛИ сбор фактов
  roles:
    - clickhouse
  vars:
    clickhouse_version: "22.3.3.44"

- name: Установка Vector
  hosts: vector
  gather_facts: yes  # ДОБАВИЛИ сбор фактов
  roles:
    - vector_role
  vars:
    clickhouse_host: "{{ hostvars['clickhouse01']['ansible_host'] }}"
    vector_sinks:
      to_clickhouse:
        type: clickhouse
        inputs: ["system_logs", "demo_metrics"]
        host: "{{ clickhouse_host }}"
        port: 8123
        database: "monitoring"
        table: "logs"

- name: Установка Lighthouse
  hosts: lighthouse
  gather_facts: yes  # ДОБАВИЛИ сбор фактов
  roles:
    - lighthouse_role
  vars:
    lighthouse_server_name: "monitoring.local"
    lighthouse_port: 80
